project:
  type: book
  output-dir: _output

book:
  title: "Database standards"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
    - sql-server-tr-veri-tabanı-standart.md
    - postgres-standards-en.md


#toc: true
#number-sections: true
#bibliography: references.bib  
  
format:
  html:
    css: styles.css
    html-math-method: katex
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm

