project:
  type: book
  output-dir: _output

book:
  title: "Database standards"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
    - tr-sql-server/main-sql-server-standart-tr.qmd
    - tr-oracle/main-tr-oracle-standart.qmd
#    - postgres-standards-en.md


toc: true
number-sections: true
bibliography: references.bib  
  
format:
  html:
    css: styles.css
    html-math-method: katex
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
    code-line-numbers: true
    number-sections: true
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
